minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - "@ai-sdk/*"
  - "@next/*"
  - "@shopify/hydrogen"
  - "@types/react"
  - "@vercel/*"
  - ai
  - eve
  - next
  - react
  - react-dom

packages:
  - "apps/*"
