import type { MenuItem } from "@/lib/shopify/types/menu";

// NOTE: This is demo data on PR #188 so the hover mega panel and mobile accordion
// can be previewed. The production default is just Shop + About with no children.
// All hrefs resolve to /search variants so every link lands somewhere.

export const defaultNavItems: MenuItem[] = [
  {
    id: "nav-shop",
    title: "Shop",
    url: "/search",
    type: "HTTP",
    items: [
      {
        id: "nav-shop-mens",
        title: "Mens",
        url: "/search?q=mens",
        type: "HTTP",
        items: [
          {
            id: "nav-shop-mens-tops",
            title: "Tops",
            url: "/search?q=mens+tops",
            type: "HTTP",
            items: [],
          },
          {
            id: "nav-shop-mens-bottoms",
            title: "Bottoms",
            url: "/search?q=mens+pants",
            type: "HTTP",
            items: [],
          },
          {
            id: "nav-shop-mens-outerwear",
            title: "Outerwear",
            url: "/search?q=jackets",
            type: "HTTP",
            items: [],
          },
          {
            id: "nav-shop-mens-shoes",
            title: "Shoes",
            url: "/search?q=mens+shoes",
            type: "HTTP",
            items: [],
          },
        ],
      },
      {
        id: "nav-shop-womens",
        title: "Womens",
        url: "/search?q=womens",
        type: "HTTP",
        items: [
          {
            id: "nav-shop-womens-tops",
            title: "Tops",
            url: "/search?q=womens+tops",
            type: "HTTP",
            items: [],
          },
          {
            id: "nav-shop-womens-dresses",
            title: "Dresses",
            url: "/search?q=dresses",
            type: "HTTP",
            items: [],
          },
          {
            id: "nav-shop-womens-bottoms",
            title: "Bottoms",
            url: "/search?q=womens+pants",
            type: "HTTP",
            items: [],
          },
          {
            id: "nav-shop-womens-shoes",
            title: "Shoes",
            url: "/search?q=womens+shoes",
            type: "HTTP",
            items: [],
          },
        ],
      },
      {
        id: "nav-shop-kids",
        title: "Kids",
        url: "/search?q=kids",
        type: "HTTP",
        items: [
          {
            id: "nav-shop-kids-boys",
            title: "Boys",
            url: "/search?q=boys",
            type: "HTTP",
            items: [],
          },
          {
            id: "nav-shop-kids-girls",
            title: "Girls",
            url: "/search?q=girls",
            type: "HTTP",
            items: [],
          },
          {
            id: "nav-shop-kids-baby",
            title: "Baby",
            url: "/search?q=baby",
            type: "HTTP",
            items: [],
          },
        ],
      },
      {
        id: "nav-shop-home",
        title: "Home",
        url: "/search?q=home",
        type: "HTTP",
        items: [
          {
            id: "nav-shop-home-bedding",
            title: "Bedding",
            url: "/search?q=bedding",
            type: "HTTP",
            items: [],
          },
          {
            id: "nav-shop-home-lighting",
            title: "Lighting",
            url: "/search?q=lighting",
            type: "HTTP",
            items: [],
          },
          {
            id: "nav-shop-home-furniture",
            title: "Furniture",
            url: "/search?q=furniture",
            type: "HTTP",
            items: [],
          },
          {
            id: "nav-shop-home-decor",
            title: "Decor",
            url: "/search?q=decor",
            type: "HTTP",
            items: [],
          },
        ],
      },
      {
        id: "nav-shop-sale",
        title: "Sale",
        url: "/search?q=sale",
        type: "HTTP",
        items: [
          {
            id: "nav-shop-sale-mens",
            title: "Mens Sale",
            url: "/search?q=mens+sale",
            type: "HTTP",
            items: [],
          },
          {
            id: "nav-shop-sale-womens",
            title: "Womens Sale",
            url: "/search?q=womens+sale",
            type: "HTTP",
            items: [],
          },
          {
            id: "nav-shop-sale-last",
            title: "Last Chance",
            url: "/search?q=clearance",
            type: "HTTP",
            items: [],
          },
        ],
      },
    ],
  },
  {
    id: "nav-collections",
    title: "Collections",
    url: "/search?q=collections",
    type: "HTTP",
    items: [
      {
        id: "nav-collections-new",
        title: "New Arrivals",
        url: "/search?q=new",
        type: "HTTP",
        items: [],
      },
      {
        id: "nav-collections-best",
        title: "Best Sellers",
        url: "/search?q=best+sellers",
        type: "HTTP",
        items: [],
      },
      {
        id: "nav-collections-curated",
        title: "Curated",
        url: "/search?q=curated",
        type: "HTTP",
        items: [
          {
            id: "nav-collections-curated-editor",
            title: "Editor's Pick",
            url: "/search?q=editors+pick",
            type: "HTTP",
            items: [],
          },
          {
            id: "nav-collections-curated-staff",
            title: "Staff Picks",
            url: "/search?q=staff+picks",
            type: "HTTP",
            items: [],
          },
          {
            id: "nav-collections-curated-limited",
            title: "Limited Edition",
            url: "/search?q=limited+edition",
            type: "HTTP",
            items: [],
          },
        ],
      },
      {
        id: "nav-collections-seasonal",
        title: "Seasonal",
        url: "/search?q=seasonal",
        type: "HTTP",
        items: [
          {
            id: "nav-collections-seasonal-spring",
            title: "Spring",
            url: "/search?q=spring",
            type: "HTTP",
            items: [],
          },
          {
            id: "nav-collections-seasonal-summer",
            title: "Summer",
            url: "/search?q=summer",
            type: "HTTP",
            items: [],
          },
          {
            id: "nav-collections-seasonal-fall",
            title: "Fall",
            url: "/search?q=fall",
            type: "HTTP",
            items: [],
          },
          {
            id: "nav-collections-seasonal-winter",
            title: "Winter",
            url: "/search?q=winter",
            type: "HTTP",
            items: [],
          },
        ],
      },
    ],
  },
  {
    id: "nav-brands",
    title: "Brands",
    url: "/search?q=brands",
    type: "HTTP",
    items: [
      {
        id: "nav-brands-founded",
        title: "Founded",
        url: "/search?q=founded",
        type: "HTTP",
        items: [],
      },
      {
        id: "nav-brands-independent",
        title: "Independent",
        url: "/search?q=independent",
        type: "HTTP",
        items: [],
      },
      {
        id: "nav-brands-heritage",
        title: "Heritage",
        url: "/search?q=heritage",
        type: "HTTP",
        items: [],
      },
      {
        id: "nav-brands-emerging",
        title: "Emerging",
        url: "/search?q=emerging",
        type: "HTTP",
        items: [],
      },
    ],
  },
  {
    id: "nav-stories",
    title: "Stories",
    url: "/search?q=stories",
    type: "HTTP",
    items: [],
  },
  {
    id: "nav-about",
    title: "About",
    url: "/about",
    type: "HTTP",
    items: [],
  },
];
